[build]
  publish = "."
  command = "echo 'Static HTML deployment - no build required'"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  # Static deployment - no runtime required

# Enhanced Phase 4 routing
[[redirects]]
  from = "/phase4"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/prediction_performance_dashboard.html" 
  status = 200

[[redirects]]
  from = "/prediction-performance-dashboard"
  to = "/prediction_performance_dashboard.html"
  status = 200

[[redirects]]
  from = "/performance"
  to = "/prediction_performance_dashboard.html"
  status = 200

# API proxy to Railway backend (Update with your Railway URL)
[[redirects]]
  from = "/api/*"
  to = "https://your-actual-railway-url.railway.app/api/:splat"
  status = 200
  force = true

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=1800"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# SPA fallback and error handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404