[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT"

[providers]
python = "3.11"