"""
Pre-Market Gap Trading Demo
============================
VERSION: v1.3.15.193.11.6.10

This script demonstrates the new pre-market gap prediction trading feature.

It shows how to:
1. Load gap predictions from overnight pipeline reports (AU/UK)
2. Analyze gap opportunities with risk assessment
3. Calculate position sizing based on gap confidence
4. Execute pre-market trades based on gap signals

Gap predictions are generated by:
- AU: SPI 200 proxy (pipelines/models/screening/spi_proxy_realtime.py)
- UK: FTSE 100 proxy (pipelines/models/screening/ftse_proxy_realtime.py)

These predictors use:
- US market closes (S&P 500, NASDAQ, DOW)
- Overnight futures (ES, NQ for AU; Z=F for UK)
- Currency impacts (AUD/USD, GBP/USD)
- Commodity prices (Oil, Iron Ore)
- VIX for confidence adjustment

USAGE:
    # Demo only (no actual trades)
    python test_pre_market_trading.py --demo
    
    # Live execution (requires running overnight pipeline first)
    python test_pre_market_trading.py --execute
    
    # Specific market only
    python test_pre_market_trading.py --market uk --execute
"""

import logging
import json
import sys
from pathlib import Path
import argparse
from datetime import datetime

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('logs/pre_market_trading_demo.log'),
        logging.StreamHandler()
    ]
)

logger = logging.getLogger(__name__)

# Import the pre-market strategy and coordinator
try:
    from core.pre_market_strategy import PreMarketStrategy
    from core.paper_trading_coordinator import PaperTradingCoordinator
    MODULES_AVAILABLE = True
except ImportError as e:
    logger.error(f"Failed to import required modules: {e}")
    MODULES_AVAILABLE = False


def demo_gap_analysis():
    """
    Demonstrate gap analysis with sample data
    """
    logger.info("\n" + "="*80)
    logger.info("PRE-MARKET GAP TRADING DEMO")
    logger.info("="*80)
    
    # Initialize strategy
    strategy = PreMarketStrategy()
    
    # Sample UK gap prediction (from recent run)
    uk_gap = {
        'predicted_gap_pct': +0.50,  # Bullish gap
        'confidence': 70,
        'direction': 'BULLISH'
    }
    
    uk_world_risk = 87.6
    uk_sentiment = 29.2
    
    uk_top_stocks = [
        {'symbol': 'BP.L', 'prediction': 'BUY', 'confidence': 68, 'opportunity_score': 75},
        {'symbol': 'SHEL.L', 'prediction': 'BUY', 'confidence': 65, 'opportunity_score': 72},
        {'symbol': 'HSBA.L', 'prediction': 'HOLD', 'confidence': 55, 'opportunity_score': 60}
    ]
    
    logger.info("\n" + "-"*80)
    logger.info("UK MARKET SCENARIO")
    logger.info("-"*80)
    logger.info(f"Gap Prediction: {uk_gap['predicted_gap_pct']:+.2f}%")
    logger.info(f"Confidence: {uk_gap['confidence']}%")
    logger.info(f"Sentiment: {uk_sentiment:.1f}/100")
    logger.info(f"World Risk: {uk_world_risk:.1f}/100")
    logger.info(f"Analysis: Bullish gap (+0.50%) driven by commodities (oil +24.6% on Iran conflict)")
    logger.info(f"          BUT bearish sentiment (29.2) and extreme world risk (87.6)")
    logger.info(f"          Expecting: Small position entry due to mixed signals")
    
    uk_decision = strategy.analyze_gap_opportunity(
        market='uk',
        gap_prediction=uk_gap,
        world_risk_score=uk_world_risk,
        sentiment_score=uk_sentiment,
        top_stocks=uk_top_stocks
    )
    
    logger.info("\n" + "-"*80)
    logger.info("DECISION SUMMARY:")
    logger.info("-"*80)
    logger.info(f"Should Enter: {uk_decision['should_enter']}")
    if uk_decision['should_enter']:
        logger.info(f"Position Size: {uk_decision['position_multiplier']:.2f}x")
        logger.info(f"Risk Level: {uk_decision['risk_level']}")
        logger.info(f"Entry Timing: {uk_decision['timing']}")
        logger.info(f"Recommended Symbols: {', '.join(uk_decision['recommended_symbols'])}")
        logger.info(f"\nReason: {uk_decision['entry_reason']}")
        
        # Show calculation breakdown
        analysis = uk_decision['analysis']
        logger.info(f"\nPosition Calculation:")
        logger.info(f"  Base Multiplier: {analysis['base_multiplier']:.2f}x (market correlation)")
        logger.info(f"  Confidence Factor: {analysis['confidence_factor']:.2f}x (gap confidence {uk_gap['confidence']}%)")
        logger.info(f"  Gap Factor: {analysis['gap_factor']:.2f}x (gap size {uk_gap['predicted_gap_pct']:+.2f}%)")
        logger.info(f"  Risk Multiplier: {analysis['risk_multiplier']:.2f}x (world risk {uk_world_risk:.0f})")
        logger.info(f"  FINAL: {uk_decision['position_multiplier']:.2f}x")
    else:
        logger.info(f"Reason: {uk_decision['entry_reason']}")
    
    # Sample AU gap prediction
    au_gap = {
        'predicted_gap_pct': -0.57,  # Bearish gap
        'confidence': 70,
        'direction': 'BEARISH'
    }
    
    au_world_risk = 87.6
    au_sentiment = 3.4
    
    au_top_stocks = [
        {'symbol': 'BHP.AX', 'prediction': 'BUY', 'confidence': 72, 'opportunity_score': 78},
        {'symbol': 'RIO.AX', 'prediction': 'BUY', 'confidence': 70, 'opportunity_score': 75},
        {'symbol': 'CBA.AX', 'prediction': 'HOLD', 'confidence': 60, 'opportunity_score': 65}
    ]
    
    logger.info("\n\n" + "-"*80)
    logger.info("AU MARKET SCENARIO")
    logger.info("-"*80)
    logger.info(f"Gap Prediction: {au_gap['predicted_gap_pct']:+.2f}%")
    logger.info(f"Confidence: {au_gap['confidence']}%")
    logger.info(f"Sentiment: {au_sentiment:.1f}/100")
    logger.info(f"World Risk: {au_world_risk:.1f}/100")
    logger.info(f"Analysis: Bearish gap (-0.57%) with extremely bearish sentiment (3.4)")
    logger.info(f"          AND extreme world risk (87.6)")
    logger.info(f"          Expecting: Likely BLOCK due to double bearish signals + high risk")
    
    au_decision = strategy.analyze_gap_opportunity(
        market='au',
        gap_prediction=au_gap,
        world_risk_score=au_world_risk,
        sentiment_score=au_sentiment,
        top_stocks=au_top_stocks
    )
    
    logger.info("\n" + "-"*80)
    logger.info("DECISION SUMMARY:")
    logger.info("-"*80)
    logger.info(f"Should Enter: {au_decision['should_enter']}")
    if au_decision['should_enter']:
        logger.info(f"Position Size: {au_decision['position_multiplier']:.2f}x")
        logger.info(f"Risk Level: {au_decision['risk_level']}")
        logger.info(f"Entry Timing: {au_decision['timing']}")
        logger.info(f"Recommended Symbols: {', '.join(au_decision['recommended_symbols'])}")
        logger.info(f"\nReason: {au_decision['entry_reason']}")
    else:
        logger.info(f"Reason: {au_decision['entry_reason']}")
    
    logger.info("\n" + "="*80)
    logger.info("DEMO COMPLETE")
    logger.info("="*80)


def live_gap_analysis(execute: bool = False, market: str = None):
    """
    Analyze gap predictions from actual overnight pipeline reports
    
    Args:
        execute: If True, execute trades based on gap signals
        market: Specific market to analyze ('au', 'uk') or None for all
    """
    logger.info("\n" + "="*80)
    logger.info("LIVE PRE-MARKET GAP ANALYSIS")
    logger.info("="*80)
    
    # Check for overnight reports
    report_dir = Path(__file__).parent / 'reports' / 'screening'
    
    markets_to_check = [market] if market else ['au', 'uk']
    reports_found = {}
    
    for mkt in markets_to_check:
        report_path = report_dir / f'{mkt}_morning_report.json'
        if report_path.exists():
            try:
                with open(report_path, 'r') as f:
                    report = json.load(f)
                reports_found[mkt] = report
                logger.info(f"[OK] Loaded {mkt.upper()} morning report from {report_path}")
            except Exception as e:
                logger.error(f"[ERROR] Failed to load {mkt.upper()} report: {e}")
        else:
            logger.warning(f"[WARN] No {mkt.upper()} report found at {report_path}")
    
    if not reports_found:
        logger.error("No overnight reports found. Run the overnight pipelines first:")
        logger.error("  python scripts/run_au_full_pipeline.py")
        logger.error("  python scripts/run_uk_full_pipeline.py")
        return
    
    # Initialize paper trading coordinator if executing trades
    if execute:
        logger.info("\n[EXECUTE] Initializing paper trading coordinator...")
        
        # Get symbols from all reports
        all_symbols = []
        for report in reports_found.values():
            for stock in report.get('top_opportunities', report.get('top_stocks', [])):
                all_symbols.append(stock['symbol'])
        
        coordinator = PaperTradingCoordinator(
            symbols=all_symbols,
            initial_capital=100000.0,
            use_enhanced_adapter=True
        )
        
        # Run pre-market gap analysis with trade execution
        results = coordinator.analyze_pre_market_gaps(execute_trades=True)
        
        logger.info("\n" + "="*80)
        logger.info("EXECUTION RESULTS:")
        logger.info("="*80)
        
        for mkt, decision in results.items():
            logger.info(f"\n{mkt.upper()}:")
            logger.info(f"  Entered: {decision['should_enter']}")
            if decision['should_enter']:
                logger.info(f"  Positions: {len(decision['recommended_symbols'])}")
                logger.info(f"  Position Size: {decision['position_multiplier']:.2f}x")
        
        # Show current positions
        logger.info("\n" + "-"*80)
        logger.info("CURRENT POSITIONS:")
        logger.info("-"*80)
        if coordinator.positions:
            for symbol, pos in coordinator.positions.items():
                logger.info(f"  {symbol}: {pos.shares} shares @ ${pos.entry_price:.2f}")
        else:
            logger.info("  None")
    
    else:
        # Analysis only (no execution)
        strategy = PreMarketStrategy()
        
        for mkt, report in reports_found.items():
            market_sentiment = report.get('market_sentiment', {})
            gap_prediction = market_sentiment.get('gap_prediction', {})
            
            if not gap_prediction or 'predicted_gap_pct' not in gap_prediction:
                logger.warning(f"[WARN] No gap prediction in {mkt.upper()} report")
                continue
            
            sentiment_score = market_sentiment.get('sentiment_score', 50)
            world_risk = report.get('world_risk_score', 50)
            top_stocks = report.get('top_opportunities', report.get('top_stocks', []))
            
            decision = strategy.analyze_gap_opportunity(
                market=mkt,
                gap_prediction=gap_prediction,
                world_risk_score=world_risk,
                sentiment_score=sentiment_score,
                top_stocks=top_stocks
            )
            
            logger.info(f"\n{mkt.upper()} DECISION:")
            logger.info(f"  Should Enter: {decision['should_enter']}")
            if decision['should_enter']:
                logger.info(f"  Position Size: {decision['position_multiplier']:.2f}x")
                logger.info(f"  Risk: {decision['risk_level']}")
                logger.info(f"  Timing: {decision['timing']}")
                logger.info(f"  Symbols: {', '.join(decision['recommended_symbols'])}")
    
    logger.info("\n" + "="*80)
    logger.info("ANALYSIS COMPLETE")
    logger.info("="*80)


def main():
    parser = argparse.ArgumentParser(description='Pre-Market Gap Trading Demo')
    parser.add_argument('--demo', action='store_true', help='Run demo with sample data')
    parser.add_argument('--execute', action='store_true', help='Execute trades (requires overnight reports)')
    parser.add_argument('--market', type=str, choices=['au', 'uk'], help='Specific market to analyze')
    
    args = parser.parse_args()
    
    if not MODULES_AVAILABLE:
        logger.error("Required modules not available. Cannot run demo.")
        return 1
    
    # Create logs directory
    Path('logs').mkdir(exist_ok=True)
    
    if args.demo:
        demo_gap_analysis()
    else:
        live_gap_analysis(execute=args.execute, market=args.market)
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
